# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
  args = {
    name = "bailiwick-ui";
    packageName = "bailiwick-ui";
    version = "1.0.0";
    src = ./.;
    buildInputs = globalBuildInputs;
    meta = {
      description = "This is the frontend for the MBIE Regional Activity web tool.";
      homepage = "https://github.com/dragonfly-science/bailiwick-ui#readme";
      license = "";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}