name: median house price
language-config:
  subject: median house price
  labels:
    absolute-tree: median house price
    absolute: median house price
    indexed: median house price, relative to $firstYear$
themes:
  - housing
headerTitle: house price in $area$
source: REINZ
notes:
  - Annual median figures. Calendar years. Median house price data is only available for regional councils. The <a href="/theme/mean-house-value">mean house value</a> indicator is a related indicator with data for territorial authorities.
  - Source data are copyright REINZ, and are not licensed for reuse.
slices:
  - median house price
summaryTitle: median house price in $area$ in $year$
headlineNumCaption: >-
  the median house price in $area$ in $year$
localNum:
  caption: >-
    the percentage change in the median house price between
    $prevYear$ and $year$ in $area$
  transform: rate
nationalNum:
  caption: >-
    the ratio of the median house price in $area$ to the
    national median house price, in $year$
  transform: ratioNZ
units: dollars
valueType: aggregate
absoluteLabel: Price
noTA: true
charts:
  - type: map
    transforms:
      - name: absolute
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
        formatter: indexed
    order:
      - area
      - year

  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
