name: agricultural share of regional GDP
language-config:
  subject: share of GDP from agriculture
  subject-quantity: share
themes:
  - agriculture
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/economic_indicators/NationalAccounts/regional-gdp-info-releases.aspx" target="_blank">Regional GDP</a> and MBIE <a href="http://www.mbie.govt.nz/info-services/sectors-industries/regions-cities/research/modelled-territorial-authority-gross-domestic-product" target="_blank">Modelled Territorial Authority Gross Domestic Product (MTAGDP)</a>.
notes:
  - Nominal Gross Domestic Product (GDP). Regional Council estimates are derived by Statistics New Zealand, based on the Annual Enterprise Survey, Linked Employer–Employee Data, Crown Financial Information System, and Local Authority Census. Territorial Authority level GDP is modelled by MBIE. 
headerTitle: agricultural share of regional GDP in $area$
slices:
  - agriculture percentage share of regional GDP
summaryTitle: agricultural share of regional GDP in $area$, for $year$
headlineNumCaption: >-
  the agricultural share of GDP in $area$ in $year$.
localNum:
  caption: >-
    the change in the agricultural share of the GDP in $area$, between $prevYear$ and $year$.
  transform: difference
nationalNum:
  caption: >-
    the ratio of the agricultural share of the GDP in $area$ to the national share, for $year$.
  transform: ratioNZ
units: percentage
valueType: aggregate
absoluteLabel: share
charts:
  - type: map
    title: >-
      agricultural share of GDP, for $year$
    transforms:
      - name: absolute
        caption: percentage share of GDP
    facets:
      - year
  - type: timeseries
    title: agricultural share of GDP, by year
    transforms:
      - name: absolute
        caption: percentage share of GDP
      - name: indexed
        caption: share of GDP, relative to $firstYear$
    order:
      - area
      - year

  - type: barchart
    title: agricultural share of GDP, for $year$
    transforms:
      - name: absolute-tree
        caption: percentage share of GDP
    facet:
      - year

