name: area in farms
language-config:
  subject:  area used for farming
  singular: true
  labels:
    absolute-tree: farmland, hectares
    absolute: farmland, hectares
    indexed: farmland area, relative to $firstYear$
    original: the area of $area$ used for farming
    percapita: farmland area, per 10,000 people
    rate: percentage change
themes:
  - agriculture
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/industry_sectors/agriculture-horticulture-forestry/info-releases.aspx" target="_blank">Agricultural Production Statistics</a>.
notes:
  - Percentage of total land area (excluding inlet, oceanic and inland water areas) that is farmland.
headerTitle: area in farms in $year$
slices:
  - area in farms
summaryTitle: Area of $area$ that is farmland in $year$
headlineNumCaption: >-
  the area of $area$ that was used for farming in $year$.
localNum:
  caption: >-
    the percentage change in the area used for farming in $area$, between $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >-
    the percentage of the total area farmed in New Zealand that is in $area$, for $year$.
  transform: nationalPercentage
units: hectares
valueType: quantity
absoluteLabel: Area
noTA: true
charts:
  - type: map
    transforms:
      - name: rate
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
      - name: percapita
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
