name: new car registrations
language-config:
  subject-quantity: number
  subject-short: new cars first registered
  labels:
    rate: percentage change
    percapita: car registrations per 10,000 people
    absolute: number of car registrations
    absolute-tree: number of car registrations
    indexed: number of car registrations, relative to $firstYear$
themes:
  - economic
source: NZTA <a href="http://www.nzta.govt.nz/resources/registration-statistics/" target="_blank">car registrations</a>.
headerTitle: new car registrations in $area$
slices:
  - annual number of new cars first registered
summaryTitle: new cars first registered in $area$ in $year$
headlineNumCaption: >
  the number of new cars first registered in $area$ in $year$.
localNum:
  caption: >
    the percentage change in new cars first registered in $area$, from $prevYear$ to $year$.
  transform: rate
nationalNum:
  caption: >
    the percentage of the total number of new cars first registered in New Zealand which were registered in $area$, for $year$.
  transform: nationalPercentage
units: count
valueType: quantity
tooltipExtra: new cars registered
absoluteLabel: Cars
charts:
  - type: map
    transforms:
      - name: rate
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: percapita
      - name: absolute
      - name: indexed
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
