name: employment by industry
language-config:
  subject-short: people employed
  subject-quantity: number
  feature-accessor: that work in
  labels:
    absolute-tree: number of people employed
    absolute: number of people employed
    indexed: employment relative to $firstYear$
    percapita: employment per 10,000 people
    regionalPercentage: percentage of employment that is in $feature$
themes:
  - workforce
source: MBIE Detailed Regional Employment Estimates.
notes:
  - Data may be suppressed for some regions in some years. Results are subject to large sample errors, especially in smaller regions.
headerTitle: employment of $feature$ in $area$
slices:
  - employment estimates by industry (ANSIC06 L1) (incl self-employed)
summaryTitle: employment in $feature$ in $area$ in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the number of people employed [in $feature$] in $area$, in the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the percentage of employment in $area$ that is in $feature$, in the year to $yearEndMonth$ $year$.
  transform: regionalPercentage
nationalNum:
  caption: >-
    the percentage of the national employment in $feature$ that is in $area$,
    for the year to $yearEndMonth$ $year$.
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: employees
featureDropdownLabel: select an industry
topFeatureLabel: all industries
featureName: industry
barchartLabelWidth: 240
charts:
  - type: map
    transforms:
      - name: regionalPercentage
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: percapita
      - name: absolute
      - name: indexed
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
