name: employment by occupation
language-config:
  subject-quantity: number 
  subject-short: people employed
  feature-accessor: as
  labels:
    absolute-tree: number of people employed
    absolute: number of people employed
    indexed: employment relative to $firstYear$
    percapita: employment per 10,000 people
    regionalPercentage: percentage of employment that is of $feature$
themes:
  - workforce
source: MBIE Detailed Regional Employment Estimates.
notes:
  - Data may be suppressed for some regions in some years. Results are subject to large sample errors, especially in smaller regions.
headerTitle: employment in $feature$ in $area$
slices:
  - employment estimates by occupation (ANZSCO L1) (incl self-employed)
  - employment estimates by occupation (ANZSCO L1) (incl self-employed) feature sum
summaryTitle: employment in $feature$ in $area$ in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the number of people employed [as $feature$] in $area$ in the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the percentage of employment in $area$ that is of $feature$ in the year to $yearEndMonth$ $year$.
  transform: regionalPercentage
nationalNum:
  caption: >-
    the percentage of the national employment of $feature$ that is in $area$
    in the year to $yearEndMonth$ $year$.
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: employees
featureDropdownLabel: select an occupation
topFeatureLabel: all occupations
featureName: occupation
barchartLabelWidth: 240
charts:
  - type: map
    transforms:
      - name: regionalPercentage
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: percapita
      - name: absolute
      - name: indexed
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
