name: employment number
language-config:
  subject: employment number
themes:
  - workforce
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/income-and-work/employment_and_unemployment/labour-market-statistics-information-releases.aspx" target="_blank">Household Labour Force Survey</a>.
notes:
  - The employment number is the total number of employed in a region. These are annual average figures. Results are subject to large sample errors, especially in smaller regions.
headerTitle: employment number in $area$
slices:
  - employment
summaryTitle: employment number in $area$ in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the employment number in $area$ in the year to $yearEndMonth$ $year$.
localNum:
  caption: >
    the increase in employment number in $area$, between $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >
    the percentage of the employment number in $area$ in New Zealand
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: employment number
charts:
  - type: map
    title: >-
      employment number, for the year to $yearEndMonth$ $year$
    transforms:
      - name: rate
        caption: Percentage change in employment number between $prevYear$ and $year$
    facets:
      - name: year
  - type: timeseries
    title: employment number, by year
    transforms:
      - name: absolute
        caption: employment number
      - name: indexed
        caption: employment number indexed to $firstYear$
        formatter: indexed		  
    order:
      - area
      - year
  - type: barchart
    title: employment number, for the year to $yearEndMonth$ $year$
    transforms:
      - name: absolute-tree
        caption: employment number
    facets:
      - name: year
