name: housing affordability measure (Buy)
language-config:
  subject: housing affordability measure (Buy)
themes:
  - housing
source: MBIE <a href="http://www.mbie.govt.nz/info-services/housing-property/sector-information-and-statistics/housing-affordability-measure" target="_blank">Housing Affordability Measure</a>.
notes:
  - Annual average figures. Percentage of renting households in the region that, if they bought a house, would have a residual income (income less housing costs) BELOW the 2013 benchmark national median residual income for ALL households. Higher percentage means less affordable housing.
headerTitle: housing affordability measure (Buy) in $area$
slices:
  - HAM buy
summaryTitle: housing affordability measure (Buy) in $area$ in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the housing affordability measure (Buy) in $area$ in the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the change in housing affordability measure (Buy) in $area$
    between $prevYear$ and $year$ (year to $yearEndMonth$).
  transform: difference
nationalNum:
  caption: >-
    the ratio of the housing affordability measure (Buy) in $area$ to the housing affordability measure (Buy) in New Zealand, in the year to $yearEndMonth$ $year$.
  transform: ratioNZ
units: percentage
valueType: aggregate
absoluteLabel: affordability
charts:
  - type: map
    title: >-
      housing affordability measure (Buy), for the year to $yearEndMonth$ $year$
    transforms:
      - name: absolute
        caption: housing affordability measure (Buy)
    facets:
      - name: year
  - type: timeseries
    title: housing affordability measure (Buy), by year
    transforms:
      - name: absolute
        caption: housing affordability measure (Buy)
    order:
      - area
      - year
  - type: barchart
    title: housing affordability measure (Buy), for the year to $yearEndMonth$ $year$
    transforms:
      - name: absolute-tree
        caption: housing affordability measure (Buy)
    facets:
      - name: year
