name: household income distribution
language-config:
  subject-quantity: proportion
  subject-short: households with an annual income
  feature-accessor: in the range
  labels: 
    ratio-nz: ratio of the proportion households in income band to the national proportion
    original: proportion of households in income band
    difference: annual percentage point change in households in income band
    indexed: proportion of households in income band indexed to $firstYear$
themes:
  - social & income
source: Statistics New Zealand <a href="http://www.stats.govt.nz/Census/2013-census.aspx" target="_blank">Census 2013</a>.
notes:
  - Annual average household income.
headerTitle: household income distribution in $area$
slices:
  - percent household with total annual income
summaryTitle: >-
  $area$ households with annual income in the range $feature$,
  for $year$
headlineNumCaption: >-
  percentage of $area$ households with an annual income in the range $feature$,
  for $year$.
localNum:
  caption: >-
    change in percentage of $area$ households with an annual income
    in the range $feature$, between $prevYear$ and $year$.
  transform: difference
nationalNum:
  caption: >-
    proportion of $area$ households with an annual income
    in the range $feature$, relative to the national proportion, for $year$.
  transform: ratioNZ
units: percentage
valueType: aggregate
absoluteLabel: Percent
featureOrder:
  - up-to-20000
  - 20001-30000
  - 30001-50000
  - 50001-70000
  - 70001-100000
  - 100001-or-more
  - not-stated
rightChart: barchart
period: 7
charts:
  - type: map
    title: >-
      Households with income in the range $feature$, for $year$
    transforms:
      - name: absolute
        caption: Percentage of households
        formatter: percentage
    facets:
      - name: year
  - type: timeseries
    title: Change in households with income in the range $feature$
    transforms:
      - name: absolute
        caption: Percentage of households
      - name: indexed
        caption: Proportion of households, indexed to $firstYear$ 
    order:
      - area
      - year

  - type: barchart
    title: percentage of households in the income range $feature$, in $area$, for $year$
    transforms:
      - name: absolute-tree
        caption: Percentage of households
    facets:
      - name: year
    axis:
      - up-to-20000
      - 20001-30000
      - 30001-50000
      - 50001-70000
      - 70001-100000
      - 100001-or-more
      - not-stated
