name: household income (median)
language-config:
  subject: median annual household income
  labels:
    absolute-tree: median annual household income
    absolute: median annual household income
    indexed: median annual household income, relative to $firstYear$
themes:
  - social & income
headerTitle: median household income in $area$
source: MBIE Household Income Estimates (based on Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/income-and-work/Income/nz-income-survey-info-releases.aspx" target="_blank">NZ Income Survey</a> & <a href="http://www.stats.govt.nz/Census.aspx" target="_blank">Census</a>).
notes: 
  - Territorial Authority level workforce data has a break in the timeseries in 2015 due to a change in the sample method for the Household Labour Force Survey. Results are subject to large sample errors, especially in smaller regions.
  - Median annual household income.
slices:
  - median annual household income
summaryTitle: median annual household income in $area$, for $year$
headlineNumCaption: the median annual household income in $area$, for $year$.
localNum:
  caption: >
    the change in median annual household income in $area$, between $prevYear$
    and $year$.
  transform: rate
nationalNum:
  caption: >
    the median annual household income in $area$,
    relative to the New Zealand median, for $year$.
  transform: ratioNZ
units: dollars
valueType: aggregate
absoluteLabel: median income
charts:
  - type: map
    transforms:
      - name: absolute
        formatter: dollars
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
        formatter: dollars
      - name: indexed
        formatter: indexed

    order:
      - area
      - year

  - type: barchart
    transforms:
      - name: absolute-tree
        formatter: dollars
    facets:
      - name: year

