name: internet
language-config:
  subject: households with internet access
  labels:
    absolute-tree: percentage of households
    absolute: percentage of households
    indexed: proportion of households, relative to $firstYear$
themes:
  - social & income
source: Statistics New Zealand <a href="http://www.stats.govt.nz/Census.aspx">Census data</a>.
headerTitle: internet access in $area$
slices:
  - percentage of households having access to internet
summaryTitle: internet access in $area$, for $year$
headlineNumCaption: >-
   households with internet access in $area$, for $year$.
localNum:
  caption: >-
    the change in the percentage of households with access to the internet in $area$,
    between $prevYear$ and $year$. 
  transform: difference 
nationalNum:
  caption: >-
    the ratio of the percentage of households with access to the internet
    in $area$ to the national value, for $year$.
  transform: ratioNZ
units: percentage
valueType: aggregate
absoluteLabel: Internet
period: 7
charts:
  - type: map
    transforms:
      - name: absolute
        formatter: percentage
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
