name: international visitor nights
language-config:
  subject: visitor nights
  feature-accessor: by visitors from
  labels:
    absolute-tree: number of visitor nights
    absolute: number of visitor nights
    indexed: visitor nights, relative to $firstYear$
    percapita: visitor nights, per 10,000 residents
    regionalPercentage: percentage of visitor nights
themes:
  - tourism
source: MBIE <a href="http://www.mbie.govt.nz/info-services/sectors-industries/tourism/tourism-research-data/ivs" target="_blank">International Visitor Survey</a>.
notes:
  - Includes all nights by international visitors aged 15 years or more, not just those in commercial accommodation. Data may be suppressed for some regions in some years. Results are subject to large sample errors, especially in smaller regions.
headerTitle: visitor nights from $feature$ in $area$
slices:
  - international visitor nights by origin
summaryTitle: visitor nights from $feature$ in $area$, for the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the number of visitor nights from $feature$ in $area$, for the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the percentage of international visitor nights in $area$ that were from $feature$, for the year to $yearEndMonth$ $year$.
  transform: regionalPercentage
nationalNum:
  caption: >-
    the percentage of the total number of visitor nights from $feature$ that were in $area$, for the year to $yearEndMonth$ $year$.
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: nights
featureDropdownLabel: select an origin
topFeatureLabel: all international origins
rightChart: barchart
charts:
  - type: map
    transforms:
      - name: regionalPercentage
        formatter: percentage
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
      - name: percapita
    order:
      - area
      - year

  - type: barchart
    title: visitor nights in $area$, for the year to $yearEndMonth$ $year$
    transforms:
      - name: absolute-tree
    facets:
      - name: year
