name: labour force participation number
language-config:
  subject: labour force participation number
  labels:
    absolute-tree: labour force participation number
    absolute: labour force participation number
    indexed: labour force participation number indexed to $firstYear$
    rate: Percentage change in labour force participation number between $prevYear$ and $year$
themes:
  - workforce
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/income-and-work/employment_and_unemployment/labour-market-statistics-information-releases.aspx" target="_blank">Household Labour Force Survey</a>.
notes:
  - The labour force participation is the total labour force (including both employed and unemployed). These are annual average figures. Results are subject to large sample errors, especially in smaller regions.
headerTitle: labour force participation number in $area$
slices:
  - labour force participation
summaryTitle: labour force participation number in $area$ in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the labour force participation number in $area$ in the year to $yearEndMonth$ $year$.
localNum:
  caption: >
    the increase in labour force participation number in $area$, between $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >
    the percentage of the labour force participation number in $area$ in New Zealand
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: labour force participation number
charts:
  - type: map
    transforms:
      - name: rate
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
        formatter: indexed		  
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
