name: mean house value
language-config:
  subject: mean house value
  labels:
    absolute: mean house value
    indexed: mean house value, relative to $firstYear$
themes:
  - housing
source: QV.
notes: 
  - Annual average estimates of mean house values. 
  - Source data is copyright to QV and not licensed for reuse.
headerTitle: house value in $area$
slices:
  - average house value
summaryTitle: mean house value in $area$ in $year$
headlineNumCaption: >-
  the mean house value in $area$, in the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the percentage change in the mean house value between the year to $yearEndMonth$ $prevYear$ and $year$ in $area$.
  transform: rate
nationalNum:
  caption: >-
    the ratio of the mean house value in $area$, in the year to $yearEndMonth$ $year$, to the
    national mean house value.
  transform: ratioNZ
units: dollars
valueType: aggregate
absoluteLabel: value
charts:
  - type: map
    transforms:
      - name: absolute
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
        formatter: indexed
    order:
      - area
      - year

