name: NEET number
language-config:
  subject: NEET number
  labels:
    absoltute-tree: NEET number
    absolute: NEET number
    indexed: NEET number indexed to $firstYear$
    rate: Percentage change in NEET number between $prevYear$ and $year$
themes:
  - workforce
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/income-and-work/employment_and_unemployment/labour-market-statistics-information-releases.aspx" target="_blank">Household Labour Force Survey</a>.
notes:
  - The NEET number is the total number of youth (aged 15 to 24 years) who are not in education, employment, or training. These are annual average figures. Results are subject to large sample errors, especially in smaller regions.
headerTitle: NEET number in $area$
slices:
  - NEET
summaryTitle: NEET number in $area$ in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the NEET number in $area$ in the year to $yearEndMonth$ $year$.
localNum:
  caption: >
    the increase in NEET number in $area$, between $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >
    the percentage of the NEET number in $area$ in New Zealand
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: NEET number
charts:
  - type: map
    transforms:
      - name: rate
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
        formatter: indexed		  
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
