name: new building consents
language-config:
  subject: number of new building consents
themes:
  - economic
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/industry_sectors/Construction/building-consents-issued-info-releases.aspx" target="_blank">Building Consents Issued</a>.
notes: 
  - Annual number of consents issued for residential and non-residential buildings.
headerTitle: new building consents [for $feature$] in $area$
slices:
  - number of new dwelling approvals
summaryTitle: new building consents [for $feature$] in $area$ in $year$
headlineNumCaption: >-
  the number of new building consents [for $feature$] in $area$, for the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the percentage change in the number of new building consents [for $feature$] in $area$, between the year to $yearEndMonth$ $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >-
    the percentage of new building consents for $feature$ that were in $area$, for the year to $yearEndMonth$ $year$.
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: consents
noTA: true
barchartLabelWidth: 240
charts:
  - type: map
    title: >-
      change in new building consents [for $feature$] between $prevYear$
      and $year$
    transforms:
      - name: rate
        caption: percentage change
    facets:
      - year
  - type: timeseries
    title: new building consents [for $feature$] by year
    transforms:
      - name: absolute
        caption: number of consents
      - name: indexed
        caption: number of consents, relative to $firstYear$
      - name: percapita
        caption: number of consents, per 10,000 residents
    order:
      - area
      - year

  - type: barchart
    title: new building consents in $area$, for $year$
    transforms:
      - name: absolute-tree
        caption:  number of consents, per 10,000 residents
    facet:
      - year
