name: new dwellings
language-config:
  subject: number of new dwelling consents per 10,000 people
  labels:
    absolute-tree: absolute-tree
    absolute: number of consents per 10,000 people
    indexed: new dwelling consents per 10,000 people, relative to $firstYear$
themes:
  - housing
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/industry_sectors/Construction/building-consents-issued-info-releases.aspx" target="_blank">Building Consents Issued</a> and <a href="http://www.stats.govt.nz/browse_for_stats/population/estimates_and_projections/subnational-population-estimates-info-releases.aspx" target="_blank">Subnational Population Estimates</a>.
notes: 
  - Annual figures. New residential buildings.
headerTitle: new dwelling consents in $area$
slices:
  - number of residential buildings approvals per 10,000 capita
summaryTitle: new dwelling consents in $area$ in $year$
headlineNumCaption: >-
  the number of new dwelling consents per 10,000 people in $area$, for the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the percentage change in the number of new dwelling consents per 10,000 people in $area$, between the year to $yearEndMonth$ $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >-
    the ratio of the the number of new dwelling consents per 10,000 people in $area$ to the national value, for the year to $yearEndMonth$ $year$.
  transform: ratioNZ
units: count
valueType: aggregate
absoluteLabel: per 10,000
rightChart: barchart
charts:
  - type: map
    transforms:
      - name: absolute
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
    order:
      - area
      - year
  - type: barchart
    title: new dwelling consents, for $year$
    transforms:
      - name: absolute-tree
    facets:
      - name: year
