name: accommodation occupancy rate
language-config:
  subject: annual average accommodation occupancy rate
  subject-quantity: rate
themes:
  - tourism
headerTitle: accommodation occupancy rate in $area$
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/industry_sectors/accommodation/info-releases.aspx" target="_blank">Accommodation Survey</a>.
notes: 
  - Annual average figures. Carterton and South Wairarapa have combined rates, as do Whakatane and Kawerau. Rates in smaller regions are subject to larger sample errors.
slices:
  - occupancy rate
summaryTitle: accommodation occupancy rate in $area$, for $year$ 
headlineNumCaption: >-
  the annual average accommodation occupancy rate in $area$, in year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the change in the annual accommodation occupancy rate in $area$, between the year to $yearEndMonth$ $prevYear$ and $year$.
  transform: difference
nationalNum:
  caption: >-
    the ratio of the annual accommodation occupancy rate in $area$ to the national rate, in year to $yearEndMonth$ $year$.
  transform: ratioNZ
units: percentage
valueType: aggregate
absoluteLabel: Rate
charts:
  - type: map
    title: >-
      accommodation occupancy rate, for $year$
    transforms:
      - name: absolute
        caption: percentage occupancy
    facets:
      - year
  - type: timeseries
    title: accommodation occupancy rate, by year
    transforms:
      - name: absolute
        caption: percentage occupancy
      - name: indexed
        caption: occupancy, relative to $year$
    order:
      - area
      - year

  - type: barchart
    title: accommodation occupancy rate, for $year$
    transforms:
      - name: absolute-tree
        caption: percentage occupancy
    facet:
      - year
