name: population estimates
language-config:
  subject: estimated resident population
  labels:
    absolute-tree: estimated resident population
    absolute: number of people
    indexed: population, relative to $firstYear$
    rate: Percentage change in population between $prevYear$ and $year$
themes:
  - population
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/population/estimates_and_projections/subnational-pop-estimates-tables.aspx" target="_blank">Subnational Population Estimates</a>.
notes:
  - This is the estimated resident population at 30 June in each year. Subnational population estimates at 30 June were obtained by updating the census night base population of each area for births, deaths, and net migration.
headerTitle: population in $area$
slices:
  - estimated resident population
summaryTitle: population in $area$ in $year$
headlineNumCaption: the estimated resident population in $area$, at 30 June $year$.
localNum:
  caption: >
    the increase in estimated resident population in $area$, between 30 June $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >
    the percentage of the total estimated resident population for New Zealand
    that was in $area$, at 30 June $year$. 
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: population
charts:
  - type: map
    transforms:
      - name: rate
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: indexed
      - name: absolute
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
