name: primary sector shares of regional GDP
language-config:
  subject: sector shares of regional GDP
  subject-short: sector GDP share
  labels:
    absolute-tree: sector GDP share
    absolute: sector GDP share
    indexed: sector GDP share, indexed to $firstYear$
themes:
  - agriculture
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/economic_indicators/NationalAccounts/regional-gdp-info-releases.aspx" target="_blank">Regional GDP</a> and MBIE <a href="http://www.mbie.govt.nz/info-services/sectors-industries/regions-cities/research/modelled-territorial-authority-gross-domestic-product" target="_blank">Modelled Territorial Authority Gross Domestic Product (MTAGDP)</a>.
notes: 
  - Nominal Gross Domestic Product (GDP). Territorial Authority level GDP is modelled by MBIE. 2015 results are provisional estimates. 
headerTitle: the [$feature$] share of $area$ GDP 
slices:
  - primary production share of GDP by sector
summaryTitle: >-
  the [$feature$] share of $area$ GDP, for $year$
headlineNumCaption: >-
  the [$feature$] share of $area$ GDP, for $year$.
localNum:
  caption: >-
    The change in the [$feature$] share of $area$ GDP, from $prevYear$ to $year$.
  transform: difference
nationalNum:
  caption: >-
    The ratio of the [$feature$] share of $area$ GDP to the national number in $year$.
  transform: ratioNZ
units: percentage
valueType: aggregate
absoluteLabel: sector GDP share
barchartLabelWidth: 240
charts:
  - type: map
    transforms:
      - name: absolute
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
        formatter: indexed
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
