name: retail trade
language-config:
  subject: annual actual retail sales values
  labels:
      original: annual actual retail sales values in millions of dollars
      absolute: annual actual retail sales values in millions of dollars
      indexed: annual actual retail sales values indexed to $firstYear$
      absolute-tree: annual actual retail sales values
      ratio-nz: Percentage change in annual actual retail sales values between $prevYear$ and $year$
      rate: Percentage change in annual actual retail sales values between $prevYear$ and $year$
themes:
  - economic
source: Statistics New Zealand <a href="https://www.stats.govt.nz/information-releases/retail-trade-survey-march-2018-quarter" target="_blank">Retail Trade Survey</a> custom dataset.
notes:
  - The Retail Trade Survey series is based largely on GST data, that is supplemented with survey data for large businesses.
headerTitle: annual actual retail sales values in $area$
slices:
  - annual actual retail sales values
summaryTitle: annual actual retail sales values in $area$ for the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the annual actual retail sales values in $area$ for the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the percentage change in the annual actual retail sales values in $area$
    between $prevYear$ and $year$, year to $yearEndMonth$.
  transform: rate
nationalNum:
  caption: >-
    the ratio of the annual actual retail sales values in $area$ to the national value,
    for the year to $yearEndMonth$ $year$.
  transform: ratioNZ
units: milliondollars
valueType: aggregate
absoluteLabel: Actual values
charts:
  - type: map
    transforms:
      - name: rate
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
        formatter: indexed
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
