name: rural - urban proportions
language-config:
  subject-quantity: proportion
  subject-short: the population
  feature-as-subject-label: true
  labels:
    absolute-tree: Percentage of the population
    absolute: urban proportion (percentage)
    difference: percentage change
    indexed: urban proportion (relative to $firstYear$)
themes:
  - population
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/Maps_and_geography/Geographic-areas/urban-rural-profile.aspx" target="_blank">Urban/Rural Profile</a> and  <a href="http://www.stats.govt.nz/browse_for_stats/population/estimates_and_projections.aspx" target="_blank">Population Estimates</a>.
headerTitle: $feature$ proportion of population in $area$
slices:
  - per cent of urban population, by region
summaryTitle: $feature$ proportion of population in $area$ at 30 June $year$
headlineNumCaption: >-
  the $feature$ proportion of the population in $area$ at 30 June $year$.
localNum:
  caption: >-
    the change in $feature$ proportion of the population in $area$ 
    between 30 June $prevYear$ and $year$.
  transform: difference
nationalNum:
  caption: >-
   the ratio of the $feature$ proportion of the population 
   in $area$ and New Zealand, at 30 June $year$.
  transform: ratioNZ
units: percentage
valueType: aggregate
absoluteLabel: percent
charts:
  - type: map
    transforms:
      - name: difference
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
