name: school leavers by NCEA level
language-config:
  subject: school leavers
  subject-quantity: number of school leavers
  feature-accessor: with
  labels:
    absolute-tree: school leavers in $area$
    absolute: school leavers
    percapita: school leavers per 10,000 people
    percentage-tree: percentage of school leavers in $area$
    regionalPercentage: percentage of school leavers with $feature$
themes:
  - education
source: Ministry of Education <a href="http://www.educationcounts.govt.nz/statistics/schooling/senior-student-attainment/school-leavers2" target="_blank">Senior Student Attainment School Leavers</a>.
headerTitle: school leavers by NCEA level in $area$
slices:
  - school leavers by NCEA level
summaryTitle: School leavers with $feature$ in $area$ in  $year$
headlineNumCaption: >-
  the number of school leavers in $area$ with $feature$ for the year to $yearEndMonth$ $year$.
localNum:
  caption: >-
    the percentage of school leavers in $area$ with $feature$, for the year to $yearEndMonth$ $year$.
  transform: regionalPercentage
nationalNum:
  caption: >
    the perentage of all New Zealand school leavers with $feature$
    that were in $area$, in the year to $yearEndMonth$.
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: school leavers
featureName: NCEA level
featureText:
  ncea-level-1-or-above: at least NCEA level 1
  below-ncea-level-1: less than NCEA level 1
  ncea-level-2-or-above: at least NCEA level 2
  below-ncea-level-2: less than NCEA level 2
  ncea-level-3-or-above: at least NCEA level 3
  below-ncea-level-3: less than NCEA level 3
featureOrder:
  - ncea-level-3-or-above
  - ncea-level-2-or-above
  - ncea-level-1-or-above
  - below-ncea-level-3
  - below-ncea-level-2
  - below-ncea-level-1
rightChart: over-under-barchart
charts:
  - type: map
    transforms:
      - name: regionalPercentage
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: percapita
      - name: absolute
        caption: school leavers
    order:
      - area
      - year
  - type: over-under-barchart
    transforms:
      - name: percentage-tree
      - name: absolute-tree
    mapping:
      - label: Level 1
        dimensions:
          - ncea-level-1-or-above
          - below-ncea-level-1
      - label: Level 2
        dimensions:
          - ncea-level-2-or-above
          - below-ncea-level-2
      - label: Level 3
        dimensions:
          - ncea-level-3-or-above
          - below-ncea-level-3
    facets:
      - name: year

