name: provision by sub-sector
language-config:
  subject: tertiary enrolments
  feature-accessor: in
  subject-accessor: ""
  labels:
    absolute-tree: tertiary provision (EFTS and STMs)
    absolute: tertiary provision (EFTS and STMs)
    percapita: per capita tertiary provision (EFTS and STMs)
    percentage-tree: percentage of tertiary provision (EFTS and STMs)
    regionalPercentage: percentage of provision by $feature$
themes:
  - education
source: Tertiary Education Commission.
notes:
  - Equivalent full-time students (EFTS) are the main unit of measure of the consumption of education (with one student enrolled in a standard programme of study full-time for the full year equating to 1.0 EFTS).
  - Standard training measure (STM) is the main unit of measurement of the consumption of training (one STM equals the amount of training required to achieve 120 register credits).
headerTitle: tertiary provision by $feature$ in $area$
slices:
  - tertiary provision by provider
summaryTitle: tertiary provision (EFTS and STMs)[ by $feature$] in $area$, in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  tertiary provision (EFTS and STMs)[ by $feature$] in $area$, in the year to $yearEndMonth$ $year$.
localNum:
  caption: >
    the percentage of tertiary provision (EFTS and STMs) in $area$[ by $feature$], for the year to $yearEndMonth$ $year$.
  transform: regionalPercentage
nationalNum:
  caption: >
    the percentage of tertiary provision (EFTS and STMs)[ by $feature$] for New Zealand
    that was in $area$, in the year to $yearEndMonth$ $year$.
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: students
featureDropdownLabel: select a provider sub-sector
topFeatureLabel: all provider sub-sectors
featureName: provider sub-sector
barchartLabelWidth: 240
barchartTicks: 3
charts:
  - type: map
    transforms:
      - name: regionalPercentage
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: percapita
      - name: absolute
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
      - name: percentage-tree
    facets:
      - name: year


