name: enrolments by age
language-config:
  subject: tertiary enrolments
  feature-accessor: aged
  subject-accessor: ""
  labels:
    absolute-tree: tertiary enrolments
    absolute: tertiary enrolments
    indexed: tertiary enrolments, relative to $firstYear$
    percapita: per capita tertiary enrolments
    percentage-tree: percentage of tertiary enrolments
    regionalPercentage: percentage of tertiary enrolments[ aged $feature$]
themes:
  - education
source: Tertiary Education Commission.
notes:
  - Data for regions (including TAs) has been derived from a mix of student-related indicators such as secondary school location, postcode of student's term or permanent address, and provider delivery site. Numbers should be taken as indicative only.
headerTitle: tertiary enrolments[ aged $feature$] from $area$
slices:
  - tertiary enrolments by age (domestic)
summaryTitle: tertiary enrolments[ aged $feature$] from $area$, in $year$
headlineNumCaption: >-
  tertiary enrolments[ aged $feature$] from $area$, in $year$.
localNum:
  caption: >
    the percentage of tertiary enrolments from $area$[ aged $feature$], for $year$.
  transform: regionalPercentage
nationalNum:
  caption: >
    the percentage of the total tertiary enrolments for New Zealand
    that was from $area$, in $year$.
  transform: nationalPercentage
units: count
valueType: quantity
barchartTicks: 3
absoluteLabel: Age group
featureDropdownLabel: select an age group
topFeatureLabel: all age groups
featureName: age group
featureOrder:
  - under-21-years
  - 21-24-years
  - 25-years-and-over
charts:
  - type: map
    transforms:
      - name: regionalPercentage
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: percapita
      - name: absolute
      - name: indexed
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
      - name: percentage-tree
    axis:
      - under-21-years
      - 21-24-years
      - 25-years-and-over
    facets:
      - name: year


