name: underutilisation number
language-config:
  subject: underutilisation number
  labels:
    absolute-tree: underutilisation number
    absolute: underutilisation number
    indexed: underutilisation number indexed to $firstYear$
    rate: Percentage change in underutilisation number between $prevYear$ and $year$
themes:
  - workforce
source: Statistics New Zealand <a href="http://www.stats.govt.nz/browse_for_stats/income-and-work/employment_and_underutilisation/labour-market-statistics-information-releases.aspx" target="_blank">Household Labour Force Survey</a>.
notes:
  -  The underutilisation expresses the number of underutilised persons in the extended labour force, where the extended labour force is the total of the labour force (i.e. the number of persons employed and unemployed) and the potential labour force. Data may be suppressed for some regions in some years. Results are subject to large sample errors, especially in smaller regions.
headerTitle: underutilisation number in $area$
slices:
  - underutilisation
summaryTitle: underutilisation number in $area$ in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the underutilisation number in $area$ in the year to $yearEndMonth$ $year$.
localNum:
  caption: >
    the increase in underutilisation number in $area$, between $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >
    the percentage of the underutilisation number in $area$ in New Zealand
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: underutilisation number
charts:
  - type: map
    transforms:
      - name: rate
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
        formatter: indexed		  
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
