name: working age population
language-config:
  subject: working age population
  labels:
    absolute-tree: working age population
    absolute: working age population
    indexed: working age population indexed to $firstYear$
    rate: Percentage change in working age population between $prevYear$ and $year$
themes:
  - workforce
source: Statistics New Zealand <a href="http://archive.stats.govt.nz/browse_for_stats/income-and-work/employment_and_unemployment/hlfs-estimated-working-age-population-info-releases.aspx" target="_blank">Household Labour Force Survey Estimated Working-age Population</a>.
notes:
  -  The working age population is the estimate of the usually resident, non-institutionalised, population aged 15 years and over. Results are subject to large sample errors, especially in smaller regions.
headerTitle: working age population in $area$
slices:
  - working age population
summaryTitle: working age population in $area$ in the year to $yearEndMonth$ $year$
headlineNumCaption: >-
  the working age population in $area$ in the year to $yearEndMonth$ $year$.
localNum:
  caption: >
    the increase in working age population in $area$, between $prevYear$ and $year$.
  transform: rate
nationalNum:
  caption: >
    the percentage of the working age population in $area$ in New Zealand
  transform: nationalPercentage
units: count
valueType: quantity
absoluteLabel: working age population
charts:
  - type: map
    transforms:
      - name: rate
    facets:
      - name: year
  - type: timeseries
    transforms:
      - name: absolute
      - name: indexed
        formatter: indexed		  
    order:
      - area
      - year
  - type: barchart
    transforms:
      - name: absolute-tree
    facets:
      - name: year
